%% ================================================================
% STRESS TEST:
% MULTI-PARAMETER NON-LATTICE LIKELIHOOD
%
% Compare:
%   1. Direct exact observed Gaussian likelihood
%   2. Exact conditional factorization
%   3. Fast log_like_Step2c
%
% Required fixes in log_like_Step2c:
%
% (1)
% empty_depth = find(nan_r_n == size(nan_ind,2));
%
% (2)
% log_like_plus_o = ...
%   -0.5*sum(plus_o)*log(2*pi) ...
%   -sum(log(diag(L))) ...
%   -0.5*v'*v;
%
% (3) Exact verification version:
% remove additional 1e-4 I and 1e-5 I jitter
%
% ================================================================

clear;
clc;
close all;

rng(20260715);


%% ================================================================
% 0. Settings
% ================================================================

TOL = 1e-8;

% Random missing tests per case
N_RANDOM_PATTERN = 30;

% Number of fully randomized model cases
N_RANDOM_CASE = 20;

MAX_FAILURE_PRINT = 20;


assert(exist('Matern_R','file') == 2, ...
    'Cannot find Matern_R.m');

assert(exist('log_like_Step2c','file') == 2, ...
    'Cannot find log_like_Step2c.m');


%% ================================================================
% 1. Fixed stress cases
% ================================================================

cases = struct( ...
    'name', {}, ...
    'M', {}, ...
    'nh', {}, ...
    'nv', {}, ...
    'missing_rate', {}, ...
    'sof_v', {}, ...
    'sof_h', {}, ...
    'nu_v', {}, ...
    'nu_h', {}, ...
    'bhp', {}, ...
    'cs_mode', {}, ...
    'alpha_min', {}, ...
    'alpha_max', {});
cases(end+1) = make_case( ...
    'Baseline M2', ...
    2,5,12, ...
    0.15, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.30, ...
    'weak', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Low missing M2', ...
    2,5,12, ...
    0.05, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.30, ...
    'weak', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Heavy missing M2', ...
    2,7,18, ...
    0.45, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.30, ...
    'weak', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Strong Cs M2', ...
    2,6,15, ...
    0.20, ...
    0.50,3.50, ...
    0.70,1.20, ...
    0.30, ...
    'strong', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Near correlated Cs M2', ...
    2,6,15, ...
    0.25, ...
    0.50,3.50, ...
    0.70,1.20, ...
    0.30, ...
    'near', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Negative Cs M2', ...
    2,6,15, ...
    0.25, ...
    0.50,3.50, ...
    0.70,1.20, ...
    0.30, ...
    'negative', ...
    0.7,3.0);


% ---------------------------------------------------------------
% M = 3
% ---------------------------------------------------------------

cases(end+1) = make_case( ...
    'Baseline M3', ...
    3,5,12, ...
    0.15, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.30, ...
    'weak', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Heavy missing M3', ...
    3,8,16, ...
    0.40, ...
    0.40,5.00, ...
    0.60,1.50, ...
    0.30, ...
    'weak', ...
    0.5,5.0);

cases(end+1) = make_case( ...
    'Strong Cs M3', ...
    3,6,14, ...
    0.25, ...
    0.50,3.50, ...
    1.00,1.00, ...
    0.30, ...
    'strong', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Negative Cs M3', ...
    3,6,14, ...
    0.25, ...
    0.50,3.50, ...
    1.00,1.00, ...
    0.30, ...
    'negative', ...
    0.7,3.0);


% ---------------------------------------------------------------
% M = 4
% ---------------------------------------------------------------

cases(end+1) = make_case( ...
    'Baseline M4', ...
    4,5,10, ...
    0.15, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.30, ...
    'weak', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Strong Cs M4', ...
    4,6,14, ...
    0.30, ...
    0.40,5.00, ...
    0.60,1.50, ...
    0.30, ...
    'strong', ...
    0.5,5.0);


% ---------------------------------------------------------------
% Kernel extremes
% ---------------------------------------------------------------

cases(end+1) = make_case( ...
    'Short SOF', ...
    3,6,15, ...
    0.25, ...
    0.12,0.80, ...
    0.50,0.50, ...
    0.30, ...
    'weak', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Long SOF smooth', ...
    3,6,15, ...
    0.25, ...
    5.00,30.0, ...
    3.00,3.00, ...
    0.30, ...
    'weak', ...
    0.7,3.0);


% ---------------------------------------------------------------
% Variance extremes
% ---------------------------------------------------------------

cases(end+1) = make_case( ...
    'Small bhp', ...
    3,6,15, ...
    0.25, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.03, ...
    'weak', ...
    0.7,3.0);

cases(end+1) = make_case( ...
    'Large bhp', ...
    3,6,15, ...
    0.25, ...
    0.65,4.20, ...
    0.80,1.10, ...
    3.00, ...
    'weak', ...
    0.7,3.0);


% ---------------------------------------------------------------
% alpha extremes
% ---------------------------------------------------------------

cases(end+1) = make_case( ...
    'Small alpha', ...
    3,6,15, ...
    0.25, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.30, ...
    'weak', ...
    0.03,0.30);

cases(end+1) = make_case( ...
    'Large alpha', ...
    3,6,15, ...
    0.25, ...
    0.65,4.20, ...
    0.80,1.10, ...
    0.30, ...
    'weak', ...
    5.0,50.0);


%% ================================================================
% 2. Random model cases
% ================================================================

cs_modes = { ...
    'weak', ...
    'strong', ...
    'negative', ...
    'random'};

for icase = 1:N_RANDOM_CASE

    M  = randi([2,4]);
    nh = randi([4,8]);
    nv = randi([8,18]);

    missing_rate = ...
        0.05 + 0.45*rand;

    sof_v = 10^( ...
        log10(0.10) ...
        + rand*(log10(5)-log10(0.10)));

    sof_h = 10^( ...
        log10(0.50) ...
        + rand*(log10(30)-log10(0.50)));

    nu_v = ...
        0.20 + 2.80*rand;

    nu_h = ...
        0.20 + 2.80*rand;

    bhp = 10^( ...
        log10(0.03) ...
        + rand*(log10(3)-log10(0.03)));

    alpha_min = 10^( ...
        log10(0.05) ...
        + rand*(log10(2)-log10(0.05)));

    alpha_max = alpha_min * ...
        10^(0.3 + 1.5*rand);

    cs_mode = cs_modes{ ...
        randi(numel(cs_modes))};

    name = sprintf( ...
        'RandomCase%02d', ...
        icase);

    cases(end+1) = make_case( ...
        name, ...
        M,nh,nv, ...
        missing_rate, ...
        sof_v,sof_h, ...
        nu_v,nu_h, ...
        bhp, ...
        cs_mode, ...
        alpha_min,alpha_max);

end


%% ================================================================
% 3. Missing pattern types
% ================================================================

forced_patterns = { ...
    'exact_nh_missing', ...
    'full_depth_missing', ...
    'parameter_block', ...
    'hole_block', ...
    'heavy_random', ...
    'checkerboard'};


%% ================================================================
% 4. Global records
% ================================================================

all_fast_diff = [];
all_factor_diff = [];

all_case_id = [];
all_pattern = {};
all_test_id = [];

summary_result = struct([]);

failure_count = 0;
total_test = 0;


fprintf('\n');
fprintf('============================================================\n');
fprintf(' MULTI-PARAMETER NON-LATTICE LIKELIHOOD STRESS TEST\n');
fprintf('============================================================\n');

fprintf('Number of model cases = %d\n',numel(cases));
fprintf('Tolerance             = %.1e\n',TOL);


%% ================================================================
% 5. Loop over cases
% ================================================================

for icase = 1:numel(cases)

    cfg = cases(icase);

    fprintf('\n');
    fprintf('------------------------------------------------------------\n');
    fprintf('CASE %02d / %02d : %s\n', ...
        icase,numel(cases),cfg.name);

    fprintf( ...
        'M=%d, nh=%d, nv=%d, miss=%.2f, Cs=%s\n', ...
        cfg.M, ...
        cfg.nh, ...
        cfg.nv, ...
        cfg.missing_rate, ...
        cfg.cs_mode);


    %% ------------------------------------------------------------
    % Coordinates
    % -------------------------------------------------------------

    M  = cfg.M;
    nh = cfg.nh;
    nv = cfg.nv;

    x = linspace(0,12,nh)';

    x = x ...
        + 0.10*sin((1:nh)');

    y = 0.8*cos( ...
        (1:nh)'*0.73);

    z = linspace(1.5,5.0,nv)';


    %% ------------------------------------------------------------
    % Trend bases
    % -------------------------------------------------------------

    xc = (x-mean(x))/std(x);
    yc = (y-mean(y))/std(y);

    Hraw = [ ...
        ones(nh,1), ...
        xc, ...
        yc];

    phih = orth(Hraw);


    zc = (z-mean(z))/std(z);

    Zraw = [ ...
        ones(nv,1), ...
        zc, ...
        zc.^2];

    phiz = orth(Zraw);


    Y.phih = phih;
    Y.phiz = phiz;

    mh = size(phih,2);
    mz = size(phiz,2);


    %% ------------------------------------------------------------
    % Cs
    % -------------------------------------------------------------

    Cs = build_Cs( ...
        M, ...
        cfg.cs_mode);

    eigCs = eig(Cs);

    fprintf( ...
        'Cs min/max eig = %.3e / %.3e\n', ...
        min(eigCs), ...
        max(eigCs));


    %% ------------------------------------------------------------
    % Parameter eigenbasis
    % -------------------------------------------------------------

    [phi_t_Cs,omega_t_Cs] = eig(Cs);

    eigvals = diag(omega_t_Cs);

    [~,idx] = sort( ...
        eigvals, ...
        'descend');

    phi_t_Cs = ...
        phi_t_Cs(:,idx);


    %% ------------------------------------------------------------
    % alpha
    % -------------------------------------------------------------

    nw = M*mh*mz;

    alpha = exp(linspace( ...
        log(cfg.alpha_min), ...
        log(cfg.alpha_max), ...
        nw))';

    O = diag(1./alpha);


    %% ------------------------------------------------------------
    % Rv
    % -------------------------------------------------------------

    disz = abs(z'-z);

    R_v = Matern_R( ...
        cfg.nu_v, ...
        cfg.sof_v, ...
        disz);

    R_v(isnan(R_v)) = 1;

    R_v = R_v ...
        + 1e-6*eye(nv);


    %% ------------------------------------------------------------
    % Rh
    % -------------------------------------------------------------

    disx = abs(x'-x);
    disy = abs(y'-y);

    dish = sqrt( ...
        disx.^2 ...
        + disy.^2);

    R_h = Matern_R( ...
        cfg.nu_h, ...
        cfg.sof_h, ...
        dish);

    R_h(isnan(R_h)) = 1;

    R_h = R_h ...
        + 1e-6*eye(nh);


    %% ------------------------------------------------------------
    % Exact full covariance
    % -------------------------------------------------------------

    Phi = kron( ...
        phi_t_Cs, ...
        kron(phih,phiz));

    S_trend = ...
        Phi*O*Phi';

    S_res = cfg.bhp * kron( ...
        Cs, ...
        kron(R_h,R_v));

    S = S_trend + S_res;

    S = (S+S')/2;

    LS = chol(S,'lower');


    %% ------------------------------------------------------------
    % Pattern list
    % -------------------------------------------------------------

    pattern_list = [ ...
        repmat({'random'},1,N_RANDOM_PATTERN), ...
        forced_patterns];


    case_fast_diff = [];
    case_factor_diff = [];

    case_fail = 0;


    %% ============================================================
    % Individual tests
    % =============================================================

    for itest = 1:numel(pattern_list)

        total_test = total_test + 1;

        pattern_type = ...
            pattern_list{itest};


        %% --------------------------------------------------------
        % Generate NEW Gaussian sample for every test
        % ---------------------------------------------------------

        y_full = LS * ...
            randn(size(S,1),1);

        data_full = reshape( ...
            y_full, ...
            nv, ...
            nh*M);


        %% --------------------------------------------------------
        % Missing pattern
        % ---------------------------------------------------------

        missing = make_missing_pattern( ...
            nv, ...
            nh, ...
            M, ...
            cfg.missing_rate, ...
            pattern_type);


        data = data_full;

        data(missing) = NaN;

        nan_ind = isnan(data);


        try

            %% ====================================================
            % Exact direct likelihood
            % =====================================================

            obs_ind = ...
                ~nan_ind(:);

            data_vec = ...
                data(:);

            y_obs = ...
                data_vec(obs_ind);

            S_oo = ...
                S(obs_ind,obs_ind);

            S_oo = ...
                (S_oo+S_oo')/2;

            L = chol( ...
                S_oo, ...
                'lower');

            v = L\y_obs;

            logL_direct = ...
                -0.5*numel(y_obs)*log(2*pi) ...
                -sum(log(diag(L))) ...
                -0.5*(v'*v);


            %% ====================================================
            % Exact conditional factorization
            % =====================================================

            nan_r_n = ...
                sum(nan_ind,2);

            z_minus = ...
                (nan_r_n == 0);

            z_plus = ...
                (nan_r_n > 0);


            minus = false( ...
                nv, ...
                nh*M);

            minus(z_minus,:) = true;

            idx_minus = ...
                minus(:);


            plus_o = false( ...
                nv, ...
                nh*M);

            plus_o(z_plus,:) = ...
                ~nan_ind(z_plus,:);

            idx_plus_o = ...
                plus_o(:);


            y_minus = ...
                data_vec(idx_minus);

            y_plus_o = ...
                data_vec(idx_plus_o);


            % p(y_minus)
            S_mm = ...
                S(idx_minus,idx_minus);

            S_mm = ...
                (S_mm+S_mm')/2;

            Lm = chol( ...
                S_mm, ...
                'lower');

            vm = Lm\y_minus;

            logL_minus = ...
                -0.5*numel(y_minus)*log(2*pi) ...
                -sum(log(diag(Lm))) ...
                -0.5*(vm'*vm);


            % p(y_plus_o | y_minus)
            S_pm = ...
                S(idx_plus_o,idx_minus);

            S_pp = ...
                S(idx_plus_o,idx_plus_o);


            tmp = Lm\y_minus;
            tmp = Lm'\tmp;

            mu_cond = ...
                S_pm*tmp;


            tmp = Lm\S_pm';
            tmp = Lm'\tmp;

            S_cond = ...
                S_pp ...
                - S_pm*tmp;

            S_cond = ...
                (S_cond+S_cond')/2;


            Lc = chol( ...
                S_cond, ...
                'lower');

            vc = Lc\( ...
                y_plus_o ...
                - mu_cond);

            logL_plus = ...
                -0.5*numel(y_plus_o)*log(2*pi) ...
                -sum(log(diag(Lc))) ...
                -0.5*(vc'*vc);

            logL_factor = ...
                logL_minus ...
                + logL_plus;


            %% ====================================================
            % Fast likelihood
            % =====================================================

            logL_fast = log_like_Step2c( ...
                data, ...
                nan_ind, ...
                x, ...
                y, ...
                z, ...
                cfg.sof_v, ...
                cfg.sof_h, ...
                cfg.nu_v, ...
                cfg.nu_h, ...
                cfg.bhp, ...
                alpha, ...
                Y, ...
                Cs);


            %% ====================================================
            % Difference
            % =====================================================

            diff_factor = ...
                logL_factor ...
                - logL_direct;

            diff_fast = ...
                logL_fast ...
                - logL_direct;


            case_factor_diff(end+1,1) = ...
                diff_factor;

            case_fast_diff(end+1,1) = ...
                diff_fast;


            all_factor_diff(end+1,1) = ...
                diff_factor;

            all_fast_diff(end+1,1) = ...
                diff_fast;

            all_case_id(end+1,1) = ...
                icase;

            all_pattern{end+1,1} = ...
                pattern_type;

            all_test_id(end+1,1) = ...
                itest;


            %% ----------------------------------------------------
            % Failure report
            % -----------------------------------------------------

            if abs(diff_fast) >= TOL

                case_fail = ...
                    case_fail + 1;

                failure_count = ...
                    failure_count + 1;


                if failure_count <= MAX_FAILURE_PRINT

                    fprintf('\n');
                    fprintf('*** FAST FAILURE %d ***\n', ...
                        failure_count);

                    fprintf( ...
                        'Case       = %s\n', ...
                        cfg.name);

                    fprintf( ...
                        'Pattern    = %s\n', ...
                        pattern_type);

                    fprintf( ...
                        'M/nh/nv    = %d / %d / %d\n', ...
                        M,nh,nv);

                    fprintf( ...
                        'N observed = %d\n', ...
                        numel(y_obs));

                    fprintf( ...
                        'N minus    = %d\n', ...
                        numel(y_minus));

                    fprintf( ...
                        'N plus     = %d\n', ...
                        numel(y_plus_o));

                    fprintf( ...
                        'Direct     = %.15f\n', ...
                        logL_direct);

                    fprintf( ...
                        'Factor     = %.15f\n', ...
                        logL_factor);

                    fprintf( ...
                        'Fast       = %.15f\n', ...
                        logL_fast);

                    fprintf( ...
                        'Factor diff= %.6e\n', ...
                        diff_factor);

                    fprintf( ...
                        'Fast diff  = %.6e\n', ...
                        diff_fast);

                    fprintf( ...
                        'Missing count/depth:\n');

                    disp( ...
                        sum(nan_ind,2)');

                end

            end


        catch ME

            case_fail = ...
                case_fail + 1;

            failure_count = ...
                failure_count + 1;

            fprintf('\n');
            fprintf('*** MATLAB ERROR ***\n');

            fprintf( ...
                'Case    = %s\n', ...
                cfg.name);

            fprintf( ...
                'Pattern = %s\n', ...
                pattern_type);

            fprintf( ...
                'Error   = %s\n', ...
                ME.message);

            all_factor_diff(end+1,1) = NaN;
            all_fast_diff(end+1,1)   = Inf;

            all_case_id(end+1,1) = ...
                icase;

            all_pattern{end+1,1} = ...
                pattern_type;

            all_test_id(end+1,1) = ...
                itest;

        end

    end


    %% ============================================================
    % Case summary
    % =============================================================

    summary_result(icase).Case = ...
        cfg.name;

    summary_result(icase).M = ...
        M;

    summary_result(icase).nh = ...
        nh;

    summary_result(icase).nv = ...
        nv;

    summary_result(icase).MissingRate = ...
        cfg.missing_rate;

    summary_result(icase).CsMode = ...
        cfg.cs_mode;

    summary_result(icase).MaxFactorDiff = ...
        max(abs(case_factor_diff),[],'omitnan');

    summary_result(icase).MaxFastDiff = ...
        max(abs(case_fast_diff),[],'omitnan');

    summary_result(icase).MeanFastDiff = ...
        mean(abs(case_fast_diff),'omitnan');

    summary_result(icase).NFail = ...
        case_fail;


    fprintf( ...
        'max factor diff = %.3e\n', ...
        summary_result(icase).MaxFactorDiff);

    fprintf( ...
        'max fast diff   = %.3e\n', ...
        summary_result(icase).MaxFastDiff);

    fprintf( ...
        'failures        = %d\n', ...
        case_fail);

end


%% ================================================================
% 6. Final summary table
% ================================================================

SummaryTable = ...
    struct2table(summary_result);

fprintf('\n\n');
fprintf('============================================================\n');
fprintf(' CASE SUMMARY\n');
fprintf('============================================================\n');

disp(SummaryTable);


%% ================================================================
% 7. Global results
% ================================================================

finite_fast = ...
    isfinite(all_fast_diff);

finite_factor = ...
    isfinite(all_factor_diff);


max_factor_diff = max( ...
    abs(all_factor_diff(finite_factor)));

mean_factor_diff = mean( ...
    abs(all_factor_diff(finite_factor)));

max_fast_diff = max( ...
    abs(all_fast_diff(finite_fast)));

mean_fast_diff = mean( ...
    abs(all_fast_diff(finite_fast)));


fprintf('\n');
fprintf('============================================================\n');
fprintf(' FINAL GLOBAL RESULTS\n');
fprintf('============================================================\n');

fprintf( ...
    'Total model cases = %d\n', ...
    numel(cases));

fprintf( ...
    'Total tests       = %d\n', ...
    total_test);

fprintf('\n');

fprintf( ...
    'max |conditional-direct|  = %.15e\n', ...
    max_factor_diff);

fprintf( ...
    'mean |conditional-direct| = %.15e\n', ...
    mean_factor_diff);

fprintf('\n');

fprintf( ...
    'max |fast-direct|         = %.15e\n', ...
    max_fast_diff);

fprintf( ...
    'mean |fast-direct|        = %.15e\n', ...
    mean_fast_diff);

fprintf('\n');

fprintf( ...
    'Number of failures        = %d\n', ...
    failure_count);


%% ================================================================
% 8. Worst case
% ================================================================

[worst_diff,worst_idx] = max( ...
    abs(all_fast_diff));

fprintf('\n');
fprintf('============================================================\n');
fprintf(' WORST FAST CASE\n');
fprintf('============================================================\n');

fprintf( ...
    'Absolute difference = %.15e\n', ...
    worst_diff);

fprintf( ...
    'Case                = %s\n', ...
    cases(all_case_id(worst_idx)).name);

fprintf( ...
    'Pattern             = %s\n', ...
    all_pattern{worst_idx});

fprintf( ...
    'Test ID             = %d\n', ...
    all_test_id(worst_idx));


%% ================================================================
% 9. PASS / FAIL
% ================================================================

fprintf('\n');
fprintf('============================================================\n');

if max_factor_diff < TOL

    fprintf( ...
        'PASS: CONDITIONAL FACTORIZATION IS EXACT.\n');

else

    fprintf( ...
        'FAIL: CONDITIONAL BENCHMARK IS WRONG.\n');

end


if failure_count == 0 ...
        && max_fast_diff < TOL

    fprintf( ...
        'PASS: FAST NON-LATTICE LIKELIHOOD IS EXACT.\n');

else

    fprintf( ...
        'FAIL: FAST NON-LATTICE LIKELIHOOD HAS ERRORS.\n');

end

fprintf('============================================================\n');


%% ================================================================
% LOCAL FUNCTIONS
% ================================================================

function cfg = make_case( ...
    name, ...
    M,nh,nv, ...
    missing_rate, ...
    sof_v,sof_h, ...
    nu_v,nu_h, ...
    bhp, ...
    cs_mode, ...
    alpha_min,alpha_max)

cfg.name = name;

cfg.M  = M;
cfg.nh = nh;
cfg.nv = nv;

cfg.missing_rate = ...
    missing_rate;

cfg.sof_v = sof_v;
cfg.sof_h = sof_h;

cfg.nu_v = nu_v;
cfg.nu_h = nu_h;

cfg.bhp = bhp;

cfg.cs_mode = ...
    cs_mode;

cfg.alpha_min = ...
    alpha_min;

cfg.alpha_max = ...
    alpha_max;

end


%% ================================================================

function Cs = build_Cs(M,mode)

switch lower(mode)

    case 'weak'

        rho = 0.20;

        R = (1-rho)*eye(M) ...
            + rho*ones(M);


    case 'strong'

        rho = 0.90;

        R = (1-rho)*eye(M) ...
            + rho*ones(M);


    case 'near'

        rho = 0.98;

        R = (1-rho)*eye(M) ...
            + rho*ones(M);


    case 'negative'

        rho = -0.65;

        first_col = ...
            rho.^(0:M-1);

        R = toeplitz(first_col);


    case 'random'

        A = randn(M);

        R = A*A' ...
            + 0.30*eye(M);

        d = sqrt(diag(R));

        R = R./(d*d');


    otherwise

        error( ...
            'Unknown Cs mode: %s', ...
            mode);

end


% Unequal marginal variances
scales = linspace( ...
    0.8, ...
    1.4, ...
    M)';

D = diag(scales);

Cs = D*R*D;

Cs = (Cs+Cs')/2;


% SPD check
if min(eig(Cs)) <= 0

    error( ...
        'Generated Cs is not SPD.');

end

end


%% ================================================================

function missing = make_missing_pattern( ...
    nv,nh,M,missing_rate,pattern_type)

ncol = nh*M;

missing = ...
    rand(nv,ncol) < missing_rate;


switch lower(pattern_type)

    %% ------------------------------------------------------------
    case 'random'
        % Use default random pattern


    %% ------------------------------------------------------------
    case 'exact_nh_missing'

        r = min(5,nv);

        missing(r,:) = false;

        idx = randperm( ...
            ncol, ...
            nh);

        missing(r,idx) = true;


    %% ------------------------------------------------------------
    case 'full_depth_missing'

        r = min(5,nv);

        missing(r,:) = true;


    %% ------------------------------------------------------------
    case 'parameter_block'

        p = M;

        cols = ...
            (p-1)*nh + (1:nh);

        row_end = max( ...
            3, ...
            floor(0.75*nv));

        rows = 3:row_end;

        missing(rows,cols) = true;


    %% ------------------------------------------------------------
    case 'hole_block'

        h = ceil(nh/2);

        cols = ...
            h + (0:M-1)*nh;

        rows = 3:nv;

        missing(rows,cols) = true;


    %% ------------------------------------------------------------
    case 'heavy_random'

        missing = ...
            rand(nv,ncol) < 0.55;


    %% ------------------------------------------------------------
    case 'checkerboard'

        missing = ...
            false(nv,ncol);

        for iz = 3:nv

            for ic = 1:ncol

                if mod(iz+ic,3) == 0

                    missing(iz,ic) = true;

                end

            end

        end


    otherwise

        error( ...
            'Unknown missing pattern: %s', ...
            pattern_type);

end


%% ---------------------------------------------------------------
% Always retain complete depth rows
% ---------------------------------------------------------------

n_complete = min(2,nv);

missing(1:n_complete,:) = false;


%% ---------------------------------------------------------------
% Ensure at least one PARTIAL non-lattice depth
% ---------------------------------------------------------------

missing_count = ...
    sum(missing,2);

partial_depth = ...
    missing_count > 0 ...
    & missing_count < ncol;

if ~any(partial_depth)

    r = min(3,nv);

    missing(r,1) = true;

end

end